apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-bcab
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-bcab
    app.kubernetes.io/part-of: test-annotations-app-zzae
  name: test-annotations-bcabhcy7
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-annotations-bcab
    weight: 100
status: {}
