apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-bcab
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-bcab
    app.kubernetes.io/part-of: test-annotations-app-zzae
  name: test-annotations-bcab
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-bcab
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-bcab
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-cjra-tenant/test-annotations-app-zzae/test-annotations-bcab@sha256:80190be7bd03cb96d4c5052307f37aff3cb301f5d5b13527312a23c95f85b35f
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
